[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["booksgraphqlapi"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "booksgraphqlapi"
  org = "choreotestaysh"
  version = "1.0.1"

